# This is a basic workflow to help you get started with Actions

name: Publish package

# Controls when the action will run. 
# Triggers the workflow on push or pull request events
on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '6.0.x'
      #    include-prerelease: true
      
      - name: Doing the things
        run: |
          $root = Get-Location
          $browsers = Join-Path $root "pw-browsers"
          $projDir = Join-Path $root "App.Console"

          [System.IO.Directory]::CreateDirectory($browsers)

          #$proj = "$projDir/App.Console.csproj"
          
          Set-Location $projDir

          # install playwright
          dotnet tool install -g Microsoft.Playwright.CLI
          
          # install browsers
          $env:PLAYWRIGHT_BROWSERS_PATH="$browsers"

          playwright install firefox

          #Set-Location $browsers
                   
          # build
          dotnet build -c Release

          #Get-ChildItem -recurse | ForEach-Object {Write-Host $_}
           
          # run
          dotnet run -c Release
        shell: pwsh
