name: Publish package

on: 
  push:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      #- uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '6.0.x'
      #    include-prerelease: true
      
      - name: Run
        run: |
          $root = Get-Location
          $browsers = Join-Path $root "pw-browsers"
          $projDir = Join-Path $root "App.Console"

          [System.IO.Directory]::CreateDirectory($browsers)
      
          #$proj = "$projDir/App.Console.csproj"
          
          Set-Location $projDir

          # install playwright
          dotnet tool install -g Microsoft.Playwright.CLI
          
          # install browsers
          $env:PLAYWRIGHT_BROWSERS_PATH="$browsers"

          playwright install firefox

          #Set-Location $browsers
                   
          # build
          dotnet build -c Release

          Set-Location $root
          Get-ChildItem -recurse | ForEach-Object {Write-Host $_}
           
          # run
          # dotnet run -c Release
        shell: pwsh
