# This is a basic workflow to help you get started with Actions

name: Publish package

# Controls when the action will run. 
# Triggers the workflow on push or pull request events
on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: x
      #  run: |
      #    apt-get update \
      #    && apt-get install wget -y \
      #    && wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
      #    && dpkg -i packages-microsoft-prod.deb \
      #    && apt-get update \
      #    && apt-get install -y powershell

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '6.0.x'
      #    include-prerelease: true
      
      - name: Doing the things
        run: |
          #run.ps1
          $root = Get-Location

          #$projDir = "App.Console"
          #$proj = "$projDir/App.Console.csproj"
          #$releaseDir = "$projDir/bin/Release/net5.0"

          Set-Location 'App.Console'

          # install playwright
          dotnet tool install -g Microsoft.Playwright.CLI
          
          # install browsers
          $env:PLAYWRIGHT_BROWSERS_PATH="$root\pw-browsers"
          playwright install

                   
          # build
          dotnet build --configuration Release

          #Get-ChildItem -recurse | ForEach-Object {Write-Host $_}
           
          # run
          dotnet run -c Release
        shell: pwsh
