# This is a basic workflow to help you get started with Actions

name: Publish package

# Controls when the action will run. 
# Triggers the workflow on push or pull request events
on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '6.0.x'
      #    include-prerelease: true
      
      - name: Build and publish package
        run: |
          $root = Get-Location

          $projDir = "App.Console"
          $proj = "$projDir/App.Console.csproj"
          $releaseDir = "$projDir/bin/Release/net6.0"

          Set-Location $projDir
          
          dotnet build --configuration Release

          Get-ChildItem -recurse | ForEach-Object {Write-Host $_}
            
          Set-Location $root
                    
          dotnet tool install -g Microsoft.Playwright.CLI
          
          playwright install webkit
          
          Set-Location $releaseDir
          
          .\App.Console.exe
        shell: pwsh
